In [4]:
import numpy as np

In [23]:
a=np.array([2,3,4,5,6,6,6,6,np.nan])

In [24]:
a


array([ 2.,  3.,  4.,  5.,  6.,  6.,  6.,  6., nan])

In [7]:
np.dtype


numpy.dtype

In [8]:
np.size

<function numpy.size(a, axis=None)>

In [9]:
a.size

9

In [10]:
a.ndim

1

In [11]:
a.shape


(9,)

In [22]:
b=np.arange(10,91,10).reshape(3,3)

In [21]:
b

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [25]:
b[:,2:] #b[:,2]

array([[30],
       [60],
       [90]])

In [28]:
b[1:2,:] #b[1]

array([[40, 50, 60]])

In [22]:
b[0:2,0:2]

array([[10, 20],
       [40, 50]])