In [1]:
import numpy as np

In [12]:
a=np.ones((3,3))

In [13]:
a.itemsize

8

In [14]:
a.data[:2]

In [28]:
a=np.linspace(1,2,2,endpoint=False)

In [29]:
a

array([1. , 1.5])

In [30]:
a.dtype

dtype('float64')

In [31]:
a.dtype.name

'float64'

In [32]:
a.ndim


1

In [33]:
a.shape

(2,)

In [34]:
a.size

2

In [35]:
a.itemsize

8

In [45]:
a.data[0]

1.0

In [46]:
a=np.array([2,3,4])

In [47]:
a.data

In [48]:
a

array([2, 3, 4])

In [49]:
a[[0,1,2]]

array([2, 3, 4])

In [50]:
a.dtype

dtype('int32')

In [51]:
a.itemsize

4

In [52]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [58]:
from numpy import pi
import sys
x=np.linspace(0,2*pi,100)

In [59]:
f=np.sin(x)

In [60]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [76]:
np.set_printoptions(formattter={'all':lambda x: 'int: '+str(-x)})  

TypeError: set_printoptions() got unexpected keyword argument 'formattter'

In [73]:
print(g)

None


In [74]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [78]:
np.set_printoptions(formatter={'all':lambda x: 'int: '+str(-x)})  

TypeError: set_printoptions() got unexpected keyword argument 'formattter'

In [79]:
np.set_printoptions(formatter={'all':lambda x: 'int: '+str(-x)})

In [80]:
a=np.arange(0,3,1)

In [81]:
a


array([int: 0, int: -1, int: -2])

In [82]:
np.set_printoptions()

In [83]:
a

array([0, 1, 2])

In [3]:
a=np.full((2,2),np.inf)

In [4]:
a

array([[inf, inf],
       [inf, inf]])

In [7]:
np.full_like(5,1)

array(1)

In [24]:
a=np.arange(6,dtype='int16')

In [27]:
b=np.full_like(a,[3,4,5,6,7,7],dtype='float32',subok=True)

In [34]:
np.full_like(a,b,dtype='int16',order='C')

array([3, 4, 5, 6, 7, 7], dtype=int16)

In [43]:
np.array(2,ndmin=2,order='F')

array([[2]])

In [45]:
b=np.array([1,2,'a'])

In [46]:
b.dtype

dtype('<U11')

In [80]:
x=np.array([(2,3.0),(4,5.0)],dtype=[('a','f4'),('b','f4')])              

In [82]:
x['a']

array([2., 4.], dtype=float32)

In [83]:
# Python Program to create a data type object 
# containing a 32 bit big-endian integer 
import numpy as np 

# i4 represents integer of size 4 byte 
# > represents big-endian byte ordering and < represents little-endian encoding. 
# dt is a dtype object 
dt = np.dtype('<i4') 

print("Byte order is:",dt.byteorder) 

print("Size is:",dt.itemsize) 

print("Data type is:",dt.name) 


Byte order is: =
Size is: 4
Data type is: int32


In [84]:
# Python program for demonstrating 
# the use of fields 
import numpy as np 

# A structured data type containing a 16-character string (in field ‘name’) 
# and a sub-array of two 64-bit floating-point number (in field ‘grades’): 

dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))]) 

# Data type of object with field grades 
print(dt['grades']) 

# Data type of object with field name 
print(dt['name']) 


('<f8', (2,))
<U16


In [22]:
# Python program to demonstrate 
# the use of data type object with structured array. 
import numpy as np 

dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))]) 

# x is a structured array with names and marks of students. 
# Data type of name of the student is np.unicode_ and 
# data type of marks is np.float(64) 
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0)),('John', (6.0, 7.0))], dtype=dt) 

print(x[1]) 
print("Grades of John are: ",x[1]['grades']) 
print("grades are: ",x['grades']) 
print("Name are:",x['name'])


('John', [6., 7.])
Grades of John are:  [6. 7.]
grades are:  [[8. 7.]
 [6. 7.]
 [6. 7.]]
Name are: ['Sarah' 'John' 'John']


In [5]:
x=np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])

In [6]:
x['a']

array([1, 3])

In [7]:
x['b']

array([2, 4])

In [19]:
np.array([[1,2],[0,4]], dtype=[('a', '<i4'), ('b', '<i4')])

array([[(1, 1), (2, 2)],
       [(0, 0), (4, 4)]], dtype=[('a', '<i4'), ('b', '<i4')])

In [11]:
y

array([[(1, 1), (2, 2)],
       [(3, 3), (4, 4)]], dtype=[('a', '<i4'), ('b', '<i4')])

In [12]:
x

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i4')])