In [1]:
import numpy as np

In [ ]:
#broadcasting

In [2]:
dist=[4000,2000,5000,1000]

In [3]:
time=[2.5,1.2,7.5,4.5 ]


In [4]:
dist1=np.array(dist)

In [5]:
time1=np.array(time)

In [6]:
speed=dist1/time1

In [8]:
speed

array([1600.        , 1666.66666667,  666.66666667,  222.22222222])

In [43]:
n=np.random.randn(2,2) #use normal distrubtion 

In [9]:
np.random.rand(2,2) #random no. 0 to <1

array([[0.21643872, 0.28374655],
       [0.48162322, 0.15660532]])

In [10]:
ages=np.random.randint(18,91,10)

In [11]:
print(ages)

[46 50 87 53 81 20 61 51 62 36]


In [12]:
np.append(ages,65)

array([46, 50, 87, 53, 81, 20, 61, 51, 62, 36, 65])

In [13]:
np.mean(ages)

54.7

In [14]:
from scipy import stats

In [15]:
stats.mode(ages)

ModeResult(mode=array([20]), count=array([1]))

In [16]:
np.median(ages)

52.0

In [17]:
a=[7,8,9,3,4,10]

In [18]:
np.median(a)

7.5